### ISSUE TITLE
[BUG] IndexBlockTest fail

### ISSUE THREAD

**Issue by VladRodionov** [VladRodionov/carrot#240]
testPutGet
Check FAILED for range [140713552690544,1] Found allocation [140711433934848,4096]
Memory corruption: address=140713552690544 size=1
java.lang.Exception: Stack trace
	at java.base/java.lang.Thread.dumpStack(Thread.java:1379)
	at org.bigbase.carrot.util.UnsafeAccess$MallocStats.checkAllocation(UnsafeAccess.java:245)
	at org.bigbase.carrot.util.UnsafeAccess.copy(UnsafeAccess.java:941)
	at org.bigbase.carrot.IndexBlock.putEmpty(IndexBlock.java:1227)
	at org.bigbase.carrot.IndexBlock.put(IndexBlock.java:1133)
	at org.bigbase.carrot.IndexBlock.put(IndexBlock.java:964)
	at org.bigbase.carrot.IndexBlock.setFirstIndexBlock(IndexBlock.java:299)
	at org.bigbase.carrot.IndexBlockTest.getIndexBlock(IndexBlockTest.java:491)
	at org.bigbase.carrot.IndexBlockTest.testPutGet(IndexBlockTest.java:84)
	at org.bigbase.carrot.IndexBlockTest.testAll(IndexBlockTest.java:48)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.junit.internal.runners.TestMethodRunner.executeMethodBody(TestMethodRunner.java:99)
	at org.junit.internal.runners.TestMethodRunner.runUnprotected(TestMethodRunner.java:81)
	at org.junit.internal.runners.BeforeAndAfterRunner.runProtected(BeforeAndAfterRunner.java:34)
	at org.junit.internal.runners.TestMethodRunner.runMethod(TestMethodRunner.java:75)
	at org.junit.internal.runners.TestMethodRunner.run(TestMethodRunner.java:45)
	at org.junit.internal.runners.TestClassMethodsRunner.invokeTestMethod(TestClassMethodsRunner.java:71)
	at org.junit.internal.runners.TestClassMethodsRunner.run(TestClassMethodsRunner.java:35)
	at org.junit.internal.runners.TestClassRunner$1.runUnprotected(TestClassRunner.java:42)
	at org.junit.internal.runners.BeforeAndAfterRunner.runProtected(BeforeAndAfterRunner.java:34)
	at org.junit.internal.runners.TestClassRunner.run(TestClassRunner.java:52)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

**Comment by VladRodionov** [comment]
The test works OK in my IDE. Seems the issue is related to a command-line mode only.

**Comment by VladRodionov** [comment]
The complain is about Commons:
`public class Commons {
  public final static long ZERO = UnsafeAccess.malloc(1);  
  static {
    UnsafeAccess.putByte(ZERO,  (byte)0);
  }`

When test is run in IDE, this reference exists, when from command-line we run ALL unit tests - it fails.

**Comment by VladRodionov** [comment]
OK, just realized the issue. We can run all tests in a command-line mode only if they all either in Memory Debug mode or they are all - not in Memory Debug mode. Mixing unit tests memory debug mode won't work when running them all in a command-line mode.

**Comment by VladRodionov** [comment]
#245 will take care of this issue.
